2023-01-26 23:45:18,006 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Configure stats pid to 40347
2023-01-26 23:45:18,006 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/.config/wandb/settings
2023-01-26 23:45:18,006 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/settings
2023-01-26 23:45:18,006 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-26 23:45:18,006 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-26 23:45:18,007 INFO    MainThread:40347 [wandb_init.py:_log_setup():478] Logging user logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234517-0iil9pk6/logs/debug.log
2023-01-26 23:45:18,007 INFO    MainThread:40347 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234517-0iil9pk6/logs/debug-internal.log
2023-01-26 23:45:18,007 INFO    MainThread:40347 [wandb_init.py:init():518] calling init triggers
2023-01-26 23:45:18,007 INFO    MainThread:40347 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'learning_rate': 5e-05, 'architecture': 'Transformer', 'dataset': 'wikitext-2', 'epochs': 4}
2023-01-26 23:45:18,007 INFO    MainThread:40347 [wandb_init.py:init():537] re-initializing run, found existing run on stack: dzeu2tsp
2023-01-26 23:45:18,008 INFO    MainThread:40347 [wandb_run.py:_finish():1844] finishing run encoder-mlm/dzeu2tsp
2023-01-26 23:45:18,009 ERROR   MainThread:40347 [jupyter.py:save_history():441] Run pip install nbformat to save notebook history
2023-01-26 23:45:18,009 INFO    MainThread:40347 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-01-26 23:45:18,009 INFO    MainThread:40347 [wandb_init.py:_jupyter_teardown():410] cleaning up jupyter logic
2023-01-26 23:45:18,009 INFO    MainThread:40347 [wandb_run.py:_atexit_cleanup():2070] got exitcode: 0
2023-01-26 23:45:18,010 INFO    MainThread:40347 [wandb_run.py:_restore():2053] restore
2023-01-26 23:45:18,010 INFO    MainThread:40347 [wandb_run.py:_restore():2059] restore done
2023-01-26 23:45:21,046 WARNING MsgRouterThr:40347 [router.py:message_loop():77] message_loop has been closed
2023-01-26 23:45:29,058 INFO    MainThread:40347 [wandb_run.py:_restore():2053] restore
2023-01-26 23:45:29,060 INFO    MainThread:40347 [wandb_run.py:_restore():2059] restore done
2023-01-26 23:45:29,086 ERROR   MainThread:40347 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2079, in _atexit_cleanup
    self._on_finish()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2308, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 288, in wait
    on_probe(probe_handle)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2273, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 550, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1835, in finish
    return self._finish(exit_code, quiet)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1850, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2090, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 259, in cleanup
    self.interface.join()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 629, in join
    super().join()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 742, in join
    _ = self._communicate_shutdown()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 552, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Configure stats pid to 40347
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/.config/wandb/settings
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/settings
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_log_setup():478] Logging user logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234617-1lf98bal/logs/debug.log
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234617-1lf98bal/logs/debug-internal.log
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2b5b88880>
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():518] calling init triggers
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'learning_rate': 5e-05, 'architecture': 'Transformer', 'dataset': 'wikitext-2', 'epochs': 4}
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():537] re-initializing run, found existing run on stack: dzeu2tsp
2023-01-26 23:46:17,664 INFO    MainThread:40347 [wandb_run.py:_finish():1844] finishing run encoder-mlm/dzeu2tsp
2023-01-26 23:46:17,664 ERROR   MainThread:40347 [jupyter.py:save_history():441] Run pip install nbformat to save notebook history
2023-01-26 23:46:17,664 INFO    MainThread:40347 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-01-26 23:46:17,664 INFO    MainThread:40347 [wandb_init.py:_jupyter_teardown():410] cleaning up jupyter logic
2023-01-26 23:46:17,672 ERROR   MainThread:40347 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 550, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1835, in finish
    return self._finish(exit_code, quiet)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1863, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 187, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 54, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
